### ISSUE TITLE
[Feature] Fix fake screen detection via matchMedia

### ISSUE THREAD

**Issue by wireguard-dev** [apify/fingerprint-suite#96] opened 2022-11-06 19:58 UTC
Fake screen width/height can be detected with 
```!matchMedia(`(device-width: ${window.screen.width}px) and (device-height: ${window.screen.height}px)`).matches```

**Comment by dekelev** [comment] 2022-11-30 14:46
Is there any way to override it with the fingerprint-injector library?

**Comment by barjin** [comment] 2022-11-30 16:01
@dekelev sadly, no - at least as of now. This injection would require parsing the media query - the domain-specific query language evaluated via the `matchMedia()` function. Since the syntax documentation is [publically available](https://www.w3.org/TR/mediaqueries-3), we can set this as a future milestone task - but again, not currently planned, sorry.

**Comment by seia-soto** [comment] 2022-12-02 00:38
How about just replacing the query with RegExp? I use the following:
```ts
  const defaultMatchMedia = matchMedia

  window.matchMedia = new Proxy(
    defaultMatchMedia,
    {
      apply (target, thisArg, argArray) {
        const [query] = argArray as string[]

        if (typeof query !== 'string') {
          return Reflect.apply(target, thisArg, argArray)
        }

        const altQuery = query
          .replace(new RegExp(`\\( *?device-width: *?${width}px *?\\)`, 'ig'), `(device-width: ${defaultWidth}px)`)
          .replace(new RegExp(`\\( *?device-height: *?${height}px *?\\)`, 'ig'), `(device-height: ${defaultHeight}px)`)

        return Reflect.apply(target, thisArg, [altQuery])
      }
    }
  )
```

**Comment by dekelev** [comment] 2022-12-02 10:23
Thanks @seia-soto, It works perfectly and is passing the CreepJS `matchMedia` test now.

**Comment by barjin** [comment] 2022-12-02 12:33
Sorry, hate to be the buzzkill here, but @seia-soto 's RegExp solution can easily lead to inconsistent results - consider the following media query:

```js
matchMedia("((device-width: 2650px) and (max-device-width: 1280px))")
// let's assume the RegExp replaces 2650px (simulated size) with 1280px (actual size)
```

This query should evaluate to `false` in every real environment (2650 > 1280) but will be `true` after the RegExp treatment. The `max-min` prefixes also require additional logic (if the `max-` value is bigger than the simulated size, map to something bigger than the actual size - and vice versa). While this still could be doable with RegExps, I'd rather see something a bit more nuanced here :)

Either way, thanks for the suggestions, will experiment with this a bit more and keep you updated :)

**Comment by B4nan** [comment] 2022-12-02 12:51
Can we maybe support at least the happy path? The few most common expressions.

**Comment by seia-soto** [comment] 2022-12-02 14:02
@barjin is reasonable. However, I believe that we can find some way someday.

**Comment by barjin** [comment] 2022-12-02 15:40
Ah, sometimes, the easiest solutions are the best. 🤦🏻 I finally got to test this out properly - and realized I cannot replicate this problem.
- for **Playwright** - see the [quick start](https://github.com/apify/fingerprint-suite#quick-start) section of the README. When creating the `BrowserContext`, you have to seed the viewport option with the `screen` object from the fingerprint - this way, Playwright will open the window with the appropriate window dimensions.
```typescript
...
 const context = await browser.newContext({
        userAgent: fingerprint.userAgent,
        locale: fingerprint.navigator.language,
        viewport: fingerprint.screen,
    });
...
```

- for **Puppeteer** - this problem is not present, Puppeteer exposes `page.setViewport()` method, which is called from our library.

That really shouldn't have taken a month. Oops 😅

**Comment by dekelev** [comment] 2022-12-02 17:33
I'm testing it with Puppeteer and the issue is reproducible consistently whenever the screen is randomized in fingerprint-injector lib, so I'm not sure how it's not reproducing at your end.

**Comment by barjin** [comment] 2022-12-07 09:03
Oh, sorry @dekelev , I was just reading the measurings wrong. However, I just released a new version (`v2.1.7`), which should be finally fixing the issue for good. Definitely let me know if this helps - or affects your scripts in any other way. Thank you for your patience everyone!

**Comment by dekelev** [comment] 2022-12-07 11:00
Thanks @barjin, very nice solution that avoids the need to patch the `matchMedia` method in the first place, but I'm still able to reproduce the issue with random generated fingerprints. I'm not able to detect yet the difference between the generated fingerprints that is playing a factor here, but I'll update if I'll find it. Do you need examples or does it reproduced at your end as well?

**Comment by dekelev** [comment] 2022-12-07 11:12
It happens like 1/3 attempts.

This is example for one that works:
```
{
  "availHeight": 807,
  "availWidth": 1440,
  "pixelDepth": 24,
  "height": 900,
  "width": 1440,
  "availTop": 25,
  "availLeft": 0,
  "colorDepth": 24,
  "innerHeight": 807,
  "outerHeight": 799,
  "outerWidth": 1350,
  "innerWidth": 1440,
  "screenX": 12,
  "pageXOffset": 0,
  "pageYOffset": 0,
  "devicePixelRatio": 1,
  "clientWidth": 0,
  "clientHeight": 18,
  "hasHDR": false
}
```

And this is example for one that doesn't work:
```
{
  "availHeight": 1440,
  "availWidth": 2560,
  "pixelDepth": 24,
  "height": 1440,
  "width": 2560,
  "availTop": 0,
  "availLeft": 1728,
  "colorDepth": 24,
  "innerHeight": 1440,
  "outerHeight": 1440,
  "outerWidth": 1848,
  "innerWidth": 2560,
  "screenX": 2440,
  "pageXOffset": 0,
  "pageYOffset": 0,
  "devicePixelRatio": 1,
  "clientWidth": 0,
  "clientHeight": 18,
  "hasHDR": false
}
```

**Comment by barjin** [comment] 2022-12-07 11:38
Cheers @dekelev , can you also share the [CreepJS screen page](https://abrahamjuliot.github.io/creepjs/tests/screen.html) text/screenshot alongside the fingerprint, when the detection goes off - so we see what exactly is tripping CreepJS? Thanks!

**Comment by dekelev** [comment] 2022-12-07 11:49
Doing this:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/4444781/206171558-0434c003-171c-4e09-9c03-fd42fa342e9a.png">

Leads to the following detection on every attempt:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/4444781/206171956-364f442c-942f-4dca-9c06-fd0a1f2e62b5.png">

**Comment by dekelev** [comment] 2022-12-07 11:56
I think it's related to `page.setViewport` that I'm running after that code, so I think it actually has no issues.

**Comment by barjin** [comment] 2022-12-07 12:15
Love to hear that! Thanks to everyone, closing this issue now - but as always, feel free to reopen in case of any doubt :) 

Peace out!

**Closed by barjin** 2022-12-07 12:15 UTC
