### ISSUE TITLE
fingerprint doesn't work with worker

### ISSUE THREAD

**Issue by gagni** [apify/fingerprint-suite#283] opened 2024-04-14 12:03 UTC
You can use a worker script to retrieve the real information and therefore have the real fingerprint, so the lib is useless.

If you look at https://bot.incolumitas.com/ in the Web Worker Navigatory section.

To find the real info, they insert a worker script "worker2.js" and via this worker, they retrieve the real information from the navigator (platform, cpu,....) and so the fingerprint is useless because the site detects the real fingerprint.

In some cases I've seen google's recaptcha_v2 scripts in workers, and so use data not masked by this fingerprint lib which just injects at browser level.

**Comment by barjin** [comment] 2024-05-06 14:28
Hello and thank you for your interest in this project!

Unfortunately, this is one of the limitations of the `fingerprint-injector` package - as of now, we don't have a good-enough method of injecting the data to the Web Worker environment. We've made some attempts with modifying the network requests coming into the Worker via Playwright, but that was way too clunky and didn't work in 100% of cases (see the discussion in https://github.com/apify/fingerprint-suite/issues/64). 

I'll close this issue as a duplicate of the one above, but feel free to propose ideas even here, if you get any. 

Cheers!

**Closed by barjin** 2024-05-06 14:28 UTC
Labels: bug, t-tooling
