### ISSUE TITLE
Generate additional parameters like battery life and add to fingerprint

### ISSUE THREAD

**Issue by osuvorova** [apify/fingerprint-suite#90] opened 2022-10-30 09:30 UTC
Add the ability to generate with  extended parameters like:
- Battery
- WebGL attributes
- vendor
- etc

Now these parameters are generated as NULL

**Comment by barjin** [comment] 2022-10-30 16:10
Hi, thanks for submitting this issue! 

Unfortunately, I cannot reproduce it. Sometimes, some fingerprint properties get generated as `null`, because the original data come from real users with real browsers - and those can sometimes run wild. Users can have specific features disabled or obscure their online presence using some browser extensions - some of these can be even cause just by using different browsers! For instance, Firefox and Safari [do not provide access](https://developer.mozilla.org/en-US/docs/Web/API/Battery_Status_API#browser_compatibility) to battery readings (try accessing `navigator.battery` in either of those browsers).

All these little differences help us create consistent browser fingerprints, which help us impersonate the real-world users better. 

I'll close this issue as wontfix, but feel free to reopen it any time (or ask any additional questions).

**Closed by barjin** 2022-10-30 16:10 UTC
